GET http://localhost:8081/posts
authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFjayIsImlhdCI6MTcwODQzNTc1NH0.NW9O5QgGrBnL9KA7ivstmZB5flbKSsZ8i90KGbW-aTQ


###

POST http://localhost:8081/login
Content-Type: application/json

{
    "username": "Jack"
}